import express from 'express';
import controller from '../controllers/IA';
import { Schemas, ValidateJoi } from '../middleware/Joi';

const router = express.Router();

/**
 * @openapi
 * tags:
 *   - name: ia
 *     description: AI recommendation endpoints
 */

/**
 * @openapi
 * /ia/recommend:
 *   post:
 *     summary: Recommend a route using Weaviate Cloud and the UPC LLM
 *     tags: [ia]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               question:
 *                 type: string
 *                 example: "I am an art enthusiast and I am looking for an easy route to do with my grandchildren"
 *               limit:
 *                 type: integer
 *                 minimum: 1
 *                 maximum: 10
 *                 example: 5
 *             required:
 *               - question
 *     responses:
 *       200:
 *         description: Recommendation generated by the LLM
 *       422:
 *         description: Validation failed
 *       500:
 *         description: IA service error
 */
router.post('/recommend', ValidateJoi(Schemas.IA.recommend), controller.recommend);

export default router;
